name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installations
        run: |
          python -m pip install jupyterlite-core==0.1.0b19 jupyterlite-pyodide-kernel==0.0.5 jupyterlab==4.2.4
          pip install -ve .
          jupyter labextension list

      - name: Move files to site_dist
        run: |
          mkdir -p site_dist
          cp README.md site_dist
          cp README.md examples

      - name: Build the docs
        run: |
          pip install IPython sphinx sphinx-rtd-theme==2.0.0 m2r2==0.3.3
          sphinx-build -M html ./docs ./docs/build -W
          cp -r docs/build/html/* site_dist

      - name: Build the JupyterLite site
        run: |
          jupyter lite build --contents examples --output-dir site_dist/jupyterlite --piplite-wheels ipysketch-lite[extra]
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site_dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
